---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: {{ include "networkset-controller.fullname" . }}
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/managed-by: Helm
    release: "{{ .Release.Name }}"
  name: {{ include "networkset-controller.fullname" . }}-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "networkset-controller.fullname" . }}-proxy
subjects:
- kind: ServiceAccount
  name: {{ include "networkset-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: {{ include "networkset-controller.fullname" . }}
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/managed-by: Helm
    release: "{{ .Release.Name }}"
  name: {{ include "networkset-controller.fullname" . }}-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "networkset-controller.fullname" . }}-metrics
subjects:
- kind: ServiceAccount
  name: {{ include "networkset-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: {{ include "networkset-controller.fullname" . }}
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/managed-by: Helm
    release: "{{ .Release.Name }}"
  name: {{ include "networkset-controller.fullname" . }}-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "networkset-controller.fullname" . }}-manager
subjects:
- kind: ServiceAccount
  name: {{ include "networkset-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}