{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.rbac.serviceAccountAnnotations }}
  annotations:
    {{- range $key, $value := .Values.rbac.serviceAccountAnnotations }}
    {{   $key }}: {{ $value | quote }}
    {{- end }}
  {{- end}}
  name: {{ include "networkset-controller.fullname" . }}
  namespace: {{ default .Release.Namespace | quote }}
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: {{ include "networkset-controller.fullname" . }}
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/managed-by: Helm
    release: "{{ .Release.Name }}"
{{- end -}}
