apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: {{ include "networkset-controller.fullname" . }}
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/managed-by: Helm
    release: "{{ .Release.Name }}"
  name: {{ include "networkset-controller.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: {{ .Values.metrics.portName | quote }}
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: {{ .Values.metrics.portName }}
  selector:
    control-plane: controller-manager
