---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - crd.projectcalico.org
  resources:
  - globalnetworkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.projectcalico.org
  resources:
  - globalnetworkpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - crd.projectcalico.org
  resources:
  - globalnetworkpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crd.projectcalico.org
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.projectcalico.org
  resources:
  - networkpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - crd.projectcalico.org
  resources:
  - networkpolicies/status
  verbs:
  - get
  - patch
  - update
